# Generated by Django 2.1.7 on 2019-03-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_user',
            name='age',
            field=models.IntegerField(blank=True, default=0, max_length=4),
        ),
    ]
