# Generated by Django 2.1.7 on 2019-03-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_model_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_user',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
