# Generated by Django 2.1.7 on 2019-03-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_model_user_age_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100)),
                ('form_content', models.TextField()),
            ],
        ),
    ]
