# Generated by Django 2.1.7 on 2019-03-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_messages_model_chat_thread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messages',
        ),
        migrations.RenameField(
            model_name='model_form',
            old_name='form_name',
            new_name='postedBy',
        ),
        migrations.RemoveField(
            model_name='model_form',
            name='form_content',
        ),
        migrations.AddField(
            model_name='model_form',
            name='bodyImage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='model_form',
            name='bodyText',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='model_form',
            name='dVoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model_form',
            name='downVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model_form',
            name='subForm',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='model_form',
            name='uVoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='model_form',
            name='upVotes',
            field=models.IntegerField(default=0),
        ),
    ]
