# Generated by Django 2.1.7 on 2019-03-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20190306_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_form',
            old_name='subForm',
            new_name='subForum',
        ),
        migrations.AlterField(
            model_name='model_form',
            name='bodyImage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='model_form',
            name='downVotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='model_form',
            name='upVotes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
